language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

jdk:
  - oraclejdk8

before_script:
    - chmod +x gradlew
#Build, and run tests
script: "./gradlew clean buildDebug"
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - GRADLE_OPTS="-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
